package com.example.ui.utils

object LanguageUtils {
    private val englishMap = mapOf(
        "app_title" to "Forgot",
        "tagline" to "Save it once. Forget nothing.",
        "search_hint" to "Search passport, Frnd, parking, medicine...",
        "greeting_morning" to "Good Morning! ☀️",
        "greeting_afternoon" to "Good Afternoon! 🌤️",
        "greeting_evening" to "Good Evening! 🌙",
        "greeting_question" to "What do you want to remember today?",
        "quick_add" to "Quick Add",
        "todays_reminders" to "Today's Reminders",
        "upcoming_reminders" to "Upcoming Reminders",
        "recent_memories" to "Recent Memories",
        "categories" to "Categories",
        "pinned_items" to "Pinned Memories",
        "no_memories_found" to "No memories found.",
        "empty_state_tip" to "Tap the Quick Add FAB to save your first memory in 5 seconds!",
        "add_memory_title" to "Remember This",
        "save_button" to "Save Memory",
        "cancel_button" to "Cancel",
        "title_label" to "Title",
        "description_label" to "Details / Description",
        "priority_label" to "Priority",
        "reminder_label" to "Reminder Date & Time",
        "category_label" to "Category",
        "archive" to "Archive",
        "unarchive" to "Unarchive",
        "delete" to "Move to Trash",
        "restore" to "Restore",
        "delete_permanently" to "Delete Permanently",
        "empty_trash" to "Empty Trash",
        "penned_successfully" to "Memory saved successfully",
        "search_tab" to "Search",
        "home_tab" to "Home",
        "add_tab" to "Remember",
        "reminders_tab" to "Reminders",
        "settings_tab" to "Settings",
        "theme" to "Theme",
        "language" to "Language",
        "export_backup" to "Export Backup (JSON)",
        "import_backup" to "Import Backup (JSON)",
        "backup_restored" to "Backup restored successfully!",
        "backup_failed" to "Backup operation failed.",
        "copied_clipboard" to "Backup JSON copied to clipboard!",
        "about" to "About",
        "about_desc" to "Forgot is a fast personal memory system. It helps you save anything under 5 seconds and retrieve it instantly under 2 seconds.",
        "completed" to "Completed",
        "active" to "Active",
        "priority_low" to "Low",
        "priority_medium" to "Medium",
        "priority_high" to "High",
        
        // Category Specific Custom Forms
        "money_amount" to "Amount (₹)",
        "money_person" to "Person Name",
        "money_status" to "Payment Status",
        "money_pending" to "Pending",
        "money_paid" to "Paid",
        "parking_floor" to "Floor Level",
        "parking_slot" to "Slot Number",
        "parking_gps" to "GPS/Location Description",
        "doc_expiry" to "Document Expiry Date",
        "med_morning" to "Morning Dose (Breakfast)",
        "med_afternoon" to "Afternoon Dose (Lunch)",
        "med_night" to "Night Dose (Dinner)",
        "wishlist_price" to "Estimated Price (₹)",
        "wishlist_url" to "Web Link / URL",
        
        // Settings/Archive/Trash subheadings
        "archive_title" to "Archive Center",
        "trash_title" to "Trash (30 Days Auto-Delete)",
        "total_memories" to "Total Memories",
        "completed_today" to "Completed Today",
        "pending_items" to "Pending Reminders"
    )

    private val teluguMap = mapOf(
        "app_title" to "Forgot (మర్చిపోయా)",
        "tagline" to "ఒక్కసారి దాచండి. మర్చిపోవద్దు.",
        "search_hint" to "పాస్‌పోర్ట్, రాహుల్, పార్కింగ్, మెడిసిన్ కోసం వెతకండి...",
        "greeting_morning" to "శుభోదయం! ☀️",
        "greeting_afternoon" to "మధ్యాహ్న వందనం! 🌤️",
        "greeting_evening" to "శుభ సాయంత్రం! 🌙",
        "greeting_question" to "ఈరోజు మీరు ఏమి గుర్తుంచుకోవాలనుకుంటున్నారు?",
        "quick_add" to "త్వరిత జోడింపు",
        "todays_reminders" to "ఈనాటి రిమైండర్లు",
        "upcoming_reminders" to "రాబోయే రిమైండర్లు",
        "recent_memories" to "ఇటీవలి జ్ఞాపకాలు",
        "categories" to "విభాగాలు",
        "pinned_items" to "పిన్ చేసినవి",
        "no_memories_found" to "ఏమీ జ్ఞాపకాలు దొరకలేదు.",
        "empty_state_tip" to "కేవలం 5 సెకన్లలో మీ మొదటి జ్ఞాపకాన్ని దాచడానికి '+' పై నొక్కండి!",
        "add_memory_title" to "జ్ఞాపకాన్ని దాచు",
        "save_button" to "భద్రపరచు",
        "cancel_button" to "రద్దు చేయి",
        "title_label" to "శీర్షిక (Title)",
        "description_label" to "వివరాలు (Details)",
        "priority_label" to "ప్రాముఖ్యత (Priority)",
        "reminder_label" to "రిమైండర్ తేదీ & సమయం",
        "category_label" to "విభాగం",
        "archive" to "ఆర్కైవ్",
        "unarchive" to "ఆర్కైవ్ నుండి తీసివేయి",
        "delete" to "చెత్తబుట్టలోకి వేయి",
        "restore" to "మరలా పునరుద్ధరించు",
        "delete_permanently" to "శాశ్వతంగా తొలగించు",
        "empty_trash" to "చెత్తబుట్టను ఖాళీ చేయి",
        "penned_successfully" to "జ్ఞాపకం విజయవంతంగా భద్రపరచబడింది",
        "search_tab" to "వెతుకులాట",
        "home_tab" to "హోమ్",
        "add_tab" to "దాచు",
        "reminders_tab" to "రిమైండర్స్",
        "settings_tab" to "సెట్టింగ్స్",
        "theme" to "థీమ్ (Theme)",
        "language" to "భాష (Language)",
        "export_backup" to "బ్యాకప్ ఎగుమతి (JSON)",
        "import_backup" to "బ్యాకప్ దిగుమతి (JSON)",
        "backup_restored" to "బ్యాకప్ విజయవంతంగా పునరుద్ధరించబడింది!",
        "backup_failed" to "బ్యాకప్ విఫలమైంది.",
        "copied_clipboard" to "బ్యాకప్ JSON క్లిప్‌బోర్డ్‌కి కాపీ చేయబడింది!",
        "about" to "గురించి (About)",
        "about_desc" to "Forgot అనేది వేగవంతమైన వ్యక్తిగత జ్ఞాపకశక్తి సహాయక యాప్. ఇది మీ జ్ఞాపకాలను కేవలం 5 సెకన్లలో భద్రపరిచి, తిరిగి 2 సెకన్లలో గుర్తిస్తుంది.",
        "completed" to "పూర్తయినది",
        "active" to "యాక్టివ్",
        "priority_low" to "తక్కువ",
        "priority_medium" to "మధ్యమం",
        "priority_high" to "ఎక్కువ",
        
        // Category Specific Custom Forms
        "money_amount" to "మొత్తం డబ్బు (₹)",
        "money_person" to "వ్యక్తి పేరు (Person)",
        "money_status" to "చెల్లింపు స్థితి (Status)",
        "money_pending" to "బాకీ ఉంది (Pending)",
        "money_paid" to "చెల్లించారు (Paid)",
        "parking_floor" to "అంతస్తు (Floor)",
        "parking_slot" to "స్లాట్ నంబర్ (Slot)",
        "parking_gps" to "స్థలం లేదా గుర్తులు (GPS)",
        "doc_expiry" to "పత్రం గడువు తేదీ (Expiry)",
        "med_morning" to "ఉదయం వేళ (Morning Dose)",
        "med_afternoon" to "మధ్యాహ్నం వేళ (Afternoon Dose)",
        "med_night" to "రాత్రి వేళ (Night Dose)",
        "wishlist_price" to "అంచనా ధర (₹)",
        "wishlist_url" to "వెబ్ లింక్ (URL)",
        
        "archive_title" to "ఆర్కైవ్ సెంటర్",
        "trash_title" to "చెత్తబుట్ట (30 రోజుల్లో తొలగింపు)",
        "total_memories" to "మొత్తం జ్ఞాపకాలు",
        "completed_today" to "ఈ రోజు పూర్తయినవి",
        "pending_items" to "రాబోయేవి"
    )

    fun getString(key: String, language: String): String {
        return if (language.lowercase() == "telugu") {
            teluguMap[key] ?: englishMap[key] ?: key
        } else {
            englishMap[key] ?: key
        }
    }
}
